<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>..\webieee.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:5173</SpaProxyServerUrl>
    <UserSecretsId>e1294841-ea46-4f42-8d10-688f7bbedf4e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>9.0.5</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebIEEE.Application\WebIEEE.Application.csproj" />
    <ProjectReference Include="..\webieee.client\webieee.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\WebIEEE.Infrastructure\WebIEEE.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net8.0\appsettings.json" />
    <Content Include="bin\Debug\net8.0\Microsoft.AspNetCore.SpaProxy.dll" />
    <Content Include="bin\Debug\net8.0\Microsoft.OpenApi.dll" />
    <Content Include="bin\Debug\net8.0\spa.proxy.json" />
    <Content Include="bin\Debug\net8.0\Swashbuckle.AspNetCore.Swagger.dll" />
    <Content Include="bin\Debug\net8.0\Swashbuckle.AspNetCore.SwaggerGen.dll" />
    <Content Include="bin\Debug\net8.0\Swashbuckle.AspNetCore.SwaggerUI.dll" />
    <Content Include="bin\Debug\net8.0\WebIEEE.Server.deps.json" />
    <Content Include="bin\Debug\net8.0\WebIEEE.Server.dll" />
    <Content Include="bin\Debug\net8.0\WebIEEE.Server.exe" />
    <Content Include="bin\Debug\net8.0\WebIEEE.Server.pdb" />
    <Content Include="bin\Debug\net8.0\WebIEEE.Server.runtimeconfig.json" />
    <Content Include="obj\Debug\net8.0\apphost.exe" />
    <Content Include="obj\Debug\net8.0\refint\WebIEEE.Server.dll" />
    <Content Include="obj\Debug\net8.0\ref\WebIEEE.Server.dll" />
    <Content Include="obj\Debug\net8.0\spa.proxy.json" />
    <Content Include="obj\Debug\net8.0\staticwebassets.build.json" />
    <Content Include="obj\Debug\net8.0\staticwebassets\msbuild.build.WebIEEE.Server.props" />
    <Content Include="obj\Debug\net8.0\staticwebassets\msbuild.buildMultiTargeting.WebIEEE.Server.props" />
    <Content Include="obj\Debug\net8.0\staticwebassets\msbuild.buildTransitive.WebIEEE.Server.props" />
    <Content Include="obj\Debug\net8.0\WebIEEE..797EB3E4.Up2Date" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.AssemblyInfoInputs.cache" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.assets.cache" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.csproj.AssemblyReference.cache" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.csproj.CoreCompileInputs.cache" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.dll" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.GeneratedMSBuildEditorConfig.editorconfig" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.genruntimeconfig.cache" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.MvcApplicationPartsAssemblyInfo.cache" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.pdb" />
    <Content Include="obj\Debug\net8.0\WebIEEE.Server.sourcelink.json" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\project.nuget.cache" />
    <Content Include="obj\project.packagespec.json" />
    <Content Include="obj\rider.project.model.nuget.info" />
    <Content Include="obj\rider.project.restore.info" />
    <Content Include="obj\WebIEEE.Server.csproj.nuget.dgspec.json" />
    <Content Include="obj\WebIEEE.Server.csproj.nuget.g.props" />
    <Content Include="obj\WebIEEE.Server.csproj.nuget.g.targets" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net8.0\WebIEEE.Server.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net8.0\WebIEEE.Server.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net8.0\WebIEEE.Server.MvcApplicationPartsAssemblyInfo.cs" />
  </ItemGroup>

</Project>
